language: node_js #设置语言

node_js: "10.16.3" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo g
#after_script前5句是把部署分支的.git文件夹保护起来，用于保留历史部署的commit日志，否则部署分支永远只有一条commit记录。
#命令里面的变量都是在Travis CI里配置过的。
after_script:
  - cd ./public
  - git init -y
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "updated blog"
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master
# E: Build LifeCycle

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - blog
